import { Router } from 'express';
import getArticle from './getArticle';
import saveArticle from './saveArticle';
import deleteArticle from './deleteArticle';
const router = Router();
// const filter = { password: 0, _v: 0 };
export default router;
router.get('/list', (req, res) => getArticle(req, res));
router.post('/save', (req, res) => saveArticle(req, res));
router.post('/delete', (req, res) => deleteArticle(req, res));
